# Generated by Django 4.0.5 on 2022-06-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
