# Generated by Django 4.0.5 on 2022-06-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
    ]
