# Generated by Django 4.0.5 on 2022-06-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_remove_post_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('I prefer not to Say', 'I prefer not to Say'), ('Female', 'Female'), ('Male', 'Male')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
