# Generated by Django 4.0.5 on 2022-06-09 09:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0014_alter_profile_gender_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('I prefer not to Say', 'I prefer not to Say'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='post_image')),
                ('like_count', models.BigIntegerField(default=0)),
                ('post_caption', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ManyToManyField(blank=True, related_name='saved_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
