# Generated by Django 4.0.5 on 2022-06-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0015_alter_profile_gender_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='image',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='like',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='post_caption',
        ),
        migrations.AddField(
            model_name='saved',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('I prefer not to Say', 'I prefer not to Say'), ('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
