# Generated by Django 4.0.5 on 2022-06-09 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_remove_saved_date_posted_remove_saved_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='date_saved',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
